server:
  port: 8080

spring:
  application:
    name: epead-api-gateway
  cloud:
    gateway:
      routes:
        - id: authUser-service
          uri: lb://EPEAD-AUTHUSER-SERVICE
          predicates:
            - Path=/epead-authuser/**
        - id: course-service
          uri: lb://EPEAD-COURSE-SERVICE
          predicates:
            - Path=/epead-course/**

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost