server:
  port: 8080

spring:
  application:
    name: epead-api-gateway
  cloud:
    gateway:
      routes:
        - id: authUser-service
          uri: http://localhost:8081/
          predicates:
            - Path=/epead-authuser/**
        - id: course-service
          uri: http://localhost:8082/
          predicates:
            - Path=/epead-course/**
