server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/ead-authuser
    username: postgres
    password: elson
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.nom-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
